swagger: "2.0"
info:
  description: "Contains all available API endpoints regarding user transactions."
  version: "1.0.0"
  title: "ARGENT BANK transactions API documentation"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v1/user"
tags:
  - name: "Transaction Module"
    description: "transactions operations"
schemes:
  - "http"
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get user transactions
      description: API for fetching a user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successully
          schema:
            $ref: "#/definitions/UserTransactions"
        "404":
          description: No Transaction Found
        "500":
          description: Internal Server Error
  /transaction/:id:
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Edit transaction details
      description: API for updating a user transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: body
          name: body
          description: Update transaction details
          required: true
          schema:
            $ref: "#/definitions/EditTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details updated successully
          schema:
            $ref: "#/definitions/EditTransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  UserTransactions:
    type: object
    properties:
      status:
        type: integer
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: number
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            balance:
              type: number
            transaction type:
              type: string
            category:
              type: string
            notes:
              type: string
    xml:
      name: "UserTransactions"
  EditTransaction:
    type: object
    properties:
      id:
        type: number
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transaction type:
        type: string
      category:
        type: string
      notes:
        type: string
  EditTransactionResponse:
    type: object
    properties:
      id:
        type: number
      transaction type:
        type: string
      category:
        type: string
      notes:
        type: string
